// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Project Repository",
            "url": "https://github.com/jdepoix/youtube-transcript-api"
        },
        "license": {
            "name": "MIT License",
            "url": "https://github.com/jdepoix/youtube-transcript-api/blob/master/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Checks if the server is running and responsive. Returns a simple status response indicating server health.\nThis endpoint can be used for monitoring and load balancer health checks.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "Server is healthy",
                        "schema": {
                            "$ref": "#/definitions/main.HealthResponse"
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/list": {
            "post": {
                "description": "Lists all available transcripts for one or more YouTube videos, including manually created and auto-generated transcripts with their metadata.\nDoes not fetch the actual transcript content, only information about what transcripts are available.\nIncludes language information, whether transcripts are translatable, and available translation languages.\nReturns an array of list results, one for each requested video.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transcripts"
                ],
                "summary": "List Available Transcripts",
                "parameters": [
                    {
                        "description": "Request containing video IDs to list transcripts for",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Available transcripts listed successfully",
                        "schema": {
                            "$ref": "#/definitions/main.TranscriptResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request (missing videoIds, invalid JSON, empty body, etc.)",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error during transcript listing",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/transcripts": {
            "post": {
                "description": "Fetches transcripts for one or more YouTube videos with optional filtering and translation.\nSupports language filtering, transcript format selection, and exclusion of auto-generated or manually-created transcripts.\nCan also translate transcripts to other languages if the transcript is marked as translatable.\nReturns an array of transcript results, one for each requested video.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transcripts"
                ],
                "summary": "Fetch Video Transcripts",
                "parameters": [
                    {
                        "description": "Request containing video IDs and optional filters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.TranscriptRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transcripts retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/main.TranscriptResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request (missing videoIds, invalid JSON, empty body, etc.)",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error during transcript fetching",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Returns the version of the youtube-transcript-api Python package being used by the server.\nThis helps verify that the correct CLI tool version is installed and accessible.\nIf the version cannot be determined, returns \"unknown\".",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Get API Version",
                "responses": {
                    "200": {
                        "description": "Version retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/main.VersionResponse"
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get version from CLI",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.ErrorResponse": {
            "description": "Standard API error response with success flag and error message",
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error contains a human-readable error message describing what went wrong.\nProvides sufficient detail for clients to understand and potentially fix the issue.\nExamples: \"videoIds is required and must not be empty\", \"Invalid JSON in request body\", etc.",
                    "type": "string",
                    "example": "videoIds is required and must not be empty"
                },
                "success": {
                    "description": "Success is always false for error responses.\nAllows clients to check response status consistently across all endpoints.",
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "main.HealthResponse": {
            "description": "Server health status indicator",
            "type": "object",
            "properties": {
                "status": {
                    "description": "Status indicates the server health status.\nAlways \"ok\" if the server is running and responding.\nUsed for monitoring, load balancer health checks, and uptime verification.",
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "main.ListRequest": {
            "description": "YouTube video transcript listing request for metadata discovery",
            "type": "object",
            "properties": {
                "videoIds": {
                    "description": "VideoIDs is a required list of YouTube video IDs to list available transcripts for.\nEach ID should be a valid YouTube video ID (typically 11 characters).\nExample: \"dQw4w9WgXcQ\" (Rick Astley - Never Gonna Give You Up)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "dQw4w9WgXcQ",
                        "jNQXAC9IVRw"
                    ]
                }
            }
        },
        "main.TranscriptRequest": {
            "description": "YouTube video transcript fetch request with optional filtering and translation",
            "type": "object",
            "properties": {
                "excludeGenerated": {
                    "description": "ExcludeGenerated, when true, excludes auto-generated transcripts from the results.\nYouTube auto-generates transcripts using speech recognition if no manual transcript exists.\nDefaults to false (includes auto-generated transcripts).",
                    "type": "boolean",
                    "default": false,
                    "example": false
                },
                "excludeManuallyCreated": {
                    "description": "ExcludeManuallyCreated, when true, excludes manually created transcripts from the results.\nDefaults to false (includes manually created transcripts).",
                    "type": "boolean",
                    "default": false,
                    "example": false
                },
                "format": {
                    "description": "Format specifies the output format for the transcript content.\nValid values: 'json' (structured with timing information), 'text' (plain text only).\nDefaults to 'json' if not specified.",
                    "type": "string",
                    "default": "json",
                    "example": "json"
                },
                "languages": {
                    "description": "Languages is an optional list of language codes to filter transcripts by (e.g., 'en', 'es', 'fr').\nIf not specified, the API defaults to English ('en').\nUse standard ISO 639-1 language codes.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "en",
                        "es",
                        "fr"
                    ]
                },
                "translate": {
                    "description": "Translate, when specified with a language code, translates the transcript to that language.\nOnly works if the transcript's isTranslatable field is true.\nExample: \"es\" translates to Spanish, \"fr\" translates to French.\nLeave empty or omit to skip translation.",
                    "type": "string",
                    "example": "es"
                },
                "videoIds": {
                    "description": "VideoIDs is a required list of YouTube video IDs to fetch transcripts for.\nEach ID should be a valid YouTube video ID (typically 11 characters).\nExample: \"dQw4w9WgXcQ\" (Rick Astley - Never Gonna Give You Up)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "dQw4w9WgXcQ",
                        "jNQXAC9IVRw"
                    ]
                }
            }
        },
        "main.TranscriptResponse": {
            "description": "Standard response wrapper for transcript API operations",
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error contains the error message if Success is false.\nEmpty or omitted if Success is true.\nProvides details about what went wrong (missing parameters, API errors, etc.).",
                    "type": "string",
                    "example": "videoIds is required and must not be empty"
                },
                "success": {
                    "description": "Success indicates whether the request was processed successfully.\nTrue if all requested transcripts were fetched/listed without errors.\nFalse if any error occurred during processing.",
                    "type": "boolean",
                    "example": true
                },
                "transcripts": {
                    "description": "Transcripts contains the response data.\nType varies based on the endpoint called:\n- For /transcripts: array of FetchTranscriptResult objects\n- For /list: array of ListTranscriptResult objects\nOnly populated if Success is true. Omitted if Success is false."
                }
            }
        },
        "main.VersionResponse": {
            "description": "Version information of the youtube-transcript-api Python CLI package",
            "type": "object",
            "properties": {
                "version": {
                    "description": "Version is the semantic version string of the youtube-transcript-api package\nbeing used by the server (e.g., \"0.6.2\", \"0.7.0\").\nHelps verify that the correct CLI tool version is installed and accessible.\nReturns \"unknown\" if the version cannot be determined.",
                    "type": "string",
                    "example": "0.6.2"
                }
            }
        }
    },
    "tags": [
        {
            "description": "System and health check endpoints",
            "name": "System"
        },
        {
            "description": "Transcript fetching and listing endpoints",
            "name": "Transcripts"
        }
    ],
    "externalDocs": {
        "description": "YouTube Transcript API GitHub Repository",
        "url": "https://github.com/jdepoix/youtube-transcript-api"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "YouTube Transcript API",
	Description:      "A REST API wrapper for fetching and listing YouTube video transcripts.\nThis API provides programmatic access to YouTube transcripts through a simple REST interface,\nleveraging the youtube-transcript-api CLI tool under the hood.\nIt supports multiple languages, transcript filtering, and translation capabilities.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
